from fastapi import FastAPI
app = FastAPI()


peliculas = [
                {"Id":"1","Título": "El Padrino", "Género": "Drama", "Año": "1972"},
                {"Id":"2","Título": "Titanic", "Género": "Romance", "Año": "1997"},
                {"Id":"3","Título": "Star Wars: Episodio IV", "Género": "Ciencia ficción", "Año": "1977"},
                {"Id":"4","Título": "El Señor de los Anillos: La Comunidad del Anillo", "Género": "Fantasía", "Año": "2001"},
                {"Id":"5","Título": "Matrix", "Género": "Acción", "Año": "1999"},
                {"Id":"6","Título": "Toy Story", "Género": "Animación", "Año": "1995"},
                {"Id":"7","Título": "Jurassic Park", "Género": "Aventura", "Año": "1993"},
                {"Id":"8","Título": "Avengers: Endgame", "Género": "Superhéroes", "Año": "2019"},
                {"Id":"9","Título": "El Rey León", "Género": "Animación", "Año": "1994"},
                {"Id":"10","Título": "Regreso al Futuro", "Género": "Ciencia ficción", "Año": "1985"},
                {"Id":"11","Título": "Harry Potter y la Piedra Filosofal", "Género": "Fantasía", "Año": "2001"},
                {"Id":"12","Título": "Forrest Gump", "Género": "Drama", "Año": "1994"},
                {"Id":"13","Título": "Los Vengadores", "Género": "Superhéroes", "Año": "2012"},
                {"Id":"14","Título": "La La Land", "Género": "Musical", "Año": "2016"},
                {"Id":"15","Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994"},
                {"Id":"16","Título": "El Resplandor", "Género": "Terror", "Año": "1980"},
                {"Id":"17","Título": "E.T. el Extraterrestre", "Género": "Ciencia ficción", "Año": "1982"},
                {"Id":"18","Título": "El Caballero de la Noche", "Género": "Acción", "Año": "2008"},
                {"Id":"19","Título": "Los Increíbles", "Género": "Animación", "Año": "2004"},
                {"Id":"20","Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013"},
                {"Id":"21","Título": "Avatar", "Género": "Ciencia ficción", "Año": "2009"},
                {"Id":"22","Título": "Gladiador", "Género": "Acción", "Año": "2000"},
                {"Id":"23","Título": "Cadena Perpetua", "Género": "Drama", "Año": "1994"},
                {"Id":"24","Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991"},
                {"Id":"25","Título": "El Club de la Lucha", "Género": "Drama", "Año": "1999"},
                {"Id":"26","Título": "El Pianista", "Género": "Drama", "Año": "2002"},
                {"Id":"27","Título": "Volver al Futuro", "Género": "Ciencia ficción", "Año": "1989"},
                {"Id":"28","Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"},
                {"Id":"29","Título": "La Lista de Schindler", "Género": "Drama", "Año": "1993"},
                {"Id":"30","Título": "Misión: Imposible", "Género": "Acción", "Año": "1996"},
                {"Id":"31","Título": "Los Juegos del Hambre", "Género": "Aventura", "Año": "2012"},
                {"Id":"32","Título": "Shrek", "Género": "Animación", "Año": "2001"},
                {"Id":"33","Título": "El Renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"34","Título": "El Laberinto del Fauno", "Género": "Fantasía", "Año": "2006"},
                {"Id":"35","Título": "El Cisne Negro", "Género": "Drama", "Año": "2010"},
                {"Id":"36","Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"},
                {"Id":"37","Título": "Los Vengadores: Infinity War", "Género": "Superhéroes", "Año": "2018"},
                {"Id":"38","Título": "El Señor de los Anillos: Las Dos Torres", "Género": "Fantasía", "Año": "2002"},
                {"Id":"39","Título": "El Señor de los Anillos: El Retorno del Rey", "Género": "Fantasía", "Año": "2003"},
                {"Id":"40","Título": "Star Wars: Episodio I - La Amenaza Fantasma", "Género": "Ciencia ficción", "Año": "1999"},
                {"Id":"41","Título": "Star Wars: Episodio II - El Ataque de los Clones", "Género": "Ciencia ficción", "Año": "2002"},
                {"Id":"42","Título": "Star Wars: Episodio III - La Venganza de los Sith", "Género": "Ciencia ficción", "Año": "2005"},
                {"Id":"43","Título": "Star Wars: Episodio VII - El Despertar de la Fuerza", "Género": "Ciencia ficción", "Año": "2015"},
                {"Id":"44","Título": "Star Wars: Episodio VIII - Los Últimos Jedi", "Género": "Ciencia ficción", "Año": "2017"},
                {"Id":"45","Título": "Star Wars: Episodio IX - El Ascenso de Skywalker", "Género": "Ciencia ficción", "Año": "2019"},
                {"Id":"46","Título": "Harry Potter y la Cámara Secreta", "Género": "Fantasía", "Año": "2002"},
                {"Id":"47","Título": "Harry Potter y el Prisionero de Azkaban", "Género": "Fantasía", "Año": "2004"},
                {"Id":"48","Título": "Harry Potter y el Cáliz de Fuego", "Género": "Fantasía", "Año": "2005"},
                {"Id":"49","Título": "Harry Potter y la Orden del Fénix", "Género": "Fantasía", "Año": "2007"},
                {"Id":"50","Título": "Harry Potter y el Misterio del Príncipe", "Género": "Fantasía", "Año": "2009"},
                {"Id":"51","Título": "Harry Potter y las Reliquias de la Muerte: Parte 1", "Género": "Fantasía", "Año": "2010"},
                {"Id":"52","Título": "Harry Potter y las Reliquias de la Muerte: Parte 2", "Género": "Fantasía", "Año": "2011"},
                {"Id":"53","Título": "El Hobbit: Un Viaje Inesperado", "Género": "Fantasía", "Año": "2012"},
                {"Id":"54","Título": "El Hobbit: La Desolación de Smaug", "Género": "Fantasía", "Año": "2013"},
                {"Id":"55","Título": "El Hobbit: La Batalla de los Cinco Ejércitos", "Género": "Fantasía", "Año": "2014"},
                {"Id":"56","Título": "En busca del arca perdida", "Género": "Aventura", "Año": "1981"},
                {"Id":"57","Título": "El templo maldito", "Género": "Aventura", "Año": "1984"},
                {"Id":"58","Título": "La última cruzada", "Género": "Aventura", "Año": "1989"},
                {"Id":"59","Título": "El reino de la calavera de cristal", "Género": "Aventura", "Año": "2008"},
                {"Id":"60","Título": "El legado", "Género": "Aventura", "Año": "2022"},
                {"Id":"61","Título": "Alien: El octavo pasajero", "Género": "Ciencia ficción", "Año": "1979"},
                {"Id":"62","Título": "Aliens: El regreso", "Género": "Ciencia ficción", "Año": "1986"},
                {"Id":"63","Título": "Alien 3", "Género": "Ciencia ficción", "Año": "1992"},
                {"Id":"64","Título": "Alien: Resurrección", "Género": "Ciencia ficción", "Año": "1997"},
                {"Id":"65","Título": "Prometheus", "Género": "Ciencia ficción", "Año": "2012"},
                {"Id":"66","Título": "Alien: Covenant", "Género": "Ciencia ficción", "Año": "2017"},
                {"Id":"67","Título": "Rápido y Furioso", "Género": "Acción", "Año": "2001"},
                {"Id":"68","Título": "2 Fast 2 Furious", "Género": "Acción", "Año": "2003"},
                {"Id":"69","Título": "Turbo Charged Prelude to 2 Fast 2 Furious", "Género": "Acción", "Año": "2003"},
                {"Id":"70","Título": "Fast & Furious: Aún más rápido", "Género": "Acción", "Año": "2009"},
                {"Id":"71","Título": "Fast & Furious 5in Control", "Género": "Acción", "Año": "2011"},
                {"Id":"72","Título": "Fast & Furious 6: A todo gas", "Género": "Acción", "Año": "2013"},
                {"Id":"73","Título": "Furious 7", "Género": "Acción", "Año": "2015"},
                {"Id":"74","Título": "Fast & Furious 8", "Género": "Acción", "Año": "2017"},
                {"Id":"75","Título": "Fast & Furious 9", "Género": "Acción", "Año": "2021"},
                {"Id":"76","Título": "Misión Imposible", "Género": "Acción", "Año": "1996"},
                {"Id":"77","Título": "Misión Imposible 2", "Género": "Acción", "Año": "2000"},
                {"Id":"78","Título": "Misión Imposible 3", "Género": "Acción", "Año": "2006"},
                {"Id":"79","Título": "Misión Imposible: Protocolo fantasma", "Género": "Acción", "Año": "2011"},
                {"Id":"80","Título": "Misión Imposible: Nación secreta", "Género": "Acción", "Año": "2015"},
                {"Id":"81","Título": "Misión Imposible: Repercusión", "Género": "Acción", "Año": "2018"},
                {"Id":"82","Título": "Acorralado", "Género": "Acción", "Año": "1982"},
                {"Id":"83","Título": "Rambo: Acorralado - Parte II", "Género": "Acción", "Año": "1985"},
                {"Id":"84","Título": "Rambo III", "Género": "Acción", "Año": "1988"},
                {"Id":"85","Título": "Rambo", "Género": "Acción", "Año": "2008"},
                {"Id":"86","Título": "Rambo: Last Blood", "Género": "Acción", "Año": "2019"},
                {"Id":"87","Título": "Iron Man", "Género": "Acción", "Año": "2008"},
                {"Id":"88","Título": "Iron Man 2", "Género": "Acción", "Año": "2010"},
                {"Id":"89","Título": "Iron Man 3", "Género": "Acción", "Año": "2013"},
                {"Id":"90","Título": "Capitán América: El primer vengador", "Género": "Acción", "Año": "2011"},
                {"Id":"91","Título": "Capitán América: El soldado de invierno", "Género": "Acción", "Año": "2014"},
                {"Id":"92","Título": "Capitán América: Civil War", "Género": "Acción", "Año": "2016"},
                {"Id":"93","Título": "Thor", "Género": "Acción", "Año": "2011"},
                {"Id":"94","Título": "Thor: Un mundo oscuro", "Género": "Acción", "Año": "2013"},
                {"Id":"95","Título": "Thor: Ragnarok", "Género": "Acción", "Año": "2017"},
                {"Id":"96","Título": "Thor: Love and Thunder", "Género": "Acción", "Año": "2022"},
                {"Id":"97","Título": "Guardianes de la Galaxia", "Género": "Acción", "Año": "2014"},
                {"Id":"98","Título": "Guardianes de la Galaxia Vol. 2", "Género": "Acción", "Año": "2017"},
                {"Id":"99","Título": "Los Vengadores", "Género": "Acción", "Año": "2012"},
                {"Id":"100","Título": "Los Vengadores: La era de Ultrón", "Género": "Acción", "Año": "2015"},
                {"Id":"101","Título": "Los Vengadores: Infinity War", "Género": "Acción", "Año": "2018"},
                {"Id":"102","Título": "Los Vengadores: Endgame", "Género": "Acción", "Año": "2019"},
                {"Id":"103","Título": "Indiana Jones y los cazadores del arca perdida", "Género": "Aventura", "Año": "1981"},
                {"Id":"104","Título": "Volver al Futuro II", "Género": "Ciencia ficción", "Año": "1989"},
                {"Id":"105","Título": "La Lista de Schindler", "Género": "Drama", "Año": "1993"},
                {"Id":"106","Título": "El Rey León 2: El tesoro de Simba", "Género": "Animación", "Año": "1998"},
                {"Id":"107","Título": "Misión Imposible: Fallout", "Género": "Acción", "Año": "2018"},
                {"Id":"108","Título": "Blade Runner", "Género": "Ciencia ficción", "Año": "1982"},
                {"Id":"109","Título": "Mujer Maravilla", "Género": "Acción", "Año": "2017"},
                {"Id":"110","Título": "Batman: El caballero de la noche asciende", "Género": "Acción", "Año": "2012"},
                {"Id":"111","Título": "Inception", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"112","Título": "Mad Max: Fury Road", "Género": "Acción", "Año": "2015"},
                {"Id":"113","Título": "La forma del agua", "Género": "Fantasía", "Año": "2017"},
                {"Id":"114","Título": "El club de la lucha", "Género": "Drama", "Año": "1999"},
                {"Id":"115","Título": "La llegada", "Género": "Ciencia ficción", "Año": "2016"},
                {"Id":"116","Título": "Cadena perpetua", "Género": "Drama", "Año": "1994"},
                {"Id":"117","Título": "La guerra de las galaxias: Episodio V - El imperio contraataca", "Género": "Ciencia ficción", "Año": "1980"},
                {"Id":"118","Título": "Los juegos del hambre: En llamas", "Género": "Aventura", "Año": "2013"},
                {"Id":"119","Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"},
                {"Id":"120","Título": "El caballero de la noche", "Género": "Acción", "Año": "2008"},
                {"Id":"121","Título": "Whiplash", "Género": "Drama", "Año": "2014"},
                {"Id":"122","Título": "El hombre araña: Un nuevo universo", "Género": "Animación", "Año": "2018"},
                {"Id":"123","Título": "La La Land", "Género": "Musical", "Año": "2016"},
                {"Id":"124","Título": "Los siete magníficos", "Género": "Aventura", "Año": "1960"},
                {"Id":"125","Título": "Los juegos del hambre: Sinsajo - Parte 1", "Género": "Aventura", "Año": "2014"},
                {"Id":"126","Título": "Parasite", "Género": "Drama", "Año": "2019"},
                {"Id":"127","Título": "El origen", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"128","Título": "Guardianes de la Galaxia Vol. 2", "Género": "Acción", "Año": "2017"},
                {"Id":"129","Título": "El show de Truman", "Género": "Drama", "Año": "1998"},
                {"Id":"130","Título": "Spirited Away", "Género": "Animación", "Año": "2001"},
                {"Id":"131","Título": "El laberinto del fauno", "Género": "Fantasía", "Año": "2006"},
                {"Id":"132","Título": "La red social", "Género": "Drama", "Año": "2010"},
                {"Id":"133","Título": "La historia sin fin", "Género": "Fantasía", "Año": "1984"},
                {"Id":"134","Título": "Guardianes de la Galaxia", "Género": "Acción", "Año": "2014"},
                {"Id":"135","Título": "Los increíbles 2", "Género": "Animación", "Año": "2018"},
                {"Id":"136","Título": "El club de la pelea", "Género": "Drama", "Año": "1999"},
                {"Id":"137","Título": "Jurassic World", "Género": "Aventura", "Año": "2015"},
                {"Id":"138","Título": "Dunkerque", "Género": "Bélica", "Año": "2017"},
                {"Id":"139","Título": "Shrek 2", "Género": "Animación", "Año": "2004"},
                {"Id":"140","Título": "Inglourious Basterds", "Género": "Bélica", "Año": "2009"},
                {"Id":"141","Título": "El gran Gatsby", "Género": "Drama", "Año": "2013"},
                {"Id":"142","Título": "El silencio de los corderos", "Género": "Suspense", "Año": "1991"},
                {"Id":"143","Título": "Coco", "Género": "Animación", "Año": "2017"},
                {"Id":"144","Título": "Origen", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"145","Título": "Black Panther", "Género": "Acción", "Año": "2018"},
                {"Id":"146","Título": "El laberinto del fauno", "Género": "Fantasía", "Año": "2006"},
                {"Id":"147","Título": "Ready Player One", "Género": "Ciencia ficción", "Año": "2018"},
                {"Id":"148","Título": "Jurassic World: El reino caído", "Género": "Aventura", "Año": "2018"},
                {"Id":"149","Título": "Cómo entrenar a tu dragón", "Género": "Animación", "Año": "2010"},
                {"Id":"150","Título": "Soy leyenda", "Género": "Ciencia ficción", "Año": "2007"},
                {"Id":"151","Título": "Blade Runner 2049", "Género": "Ciencia ficción", "Año": "2017"},
                {"Id":"152","Título": "El gran showman", "Género": "Musical", "Año": "2017"},
                {"Id":"153","Título": "El renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"154","Título": "Kung Fu Panda", "Género": "Animación", "Año": "2008"},
                {"Id":"155","Título": "Spider-Man: Homecoming", "Género": "Acción", "Año": "2017"},
                {"Id":"156","Título": "Ratatouille", "Género": "Animación", "Año": "2007"},
                {"Id":"157","Título": "La guerra de las galaxias: Episodio VI - El retorno del Jedi", "Género": "Ciencia ficción", "Año": "1983"},
                {"Id":"158","Título": "Los miserables", "Género": "Drama", "Año": "2012"},
                {"Id":"159","Título": "Mad Max: Furia en el camino", "Género": "Acción", "Año": "2015"},
                {"Id":"160","Título": "El renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"161","Título": "Coco", "Género": "Animación", "Año": "2017"},
                {"Id":"162","Título": "Baby Driver", "Género": "Acción", "Año": "2017"},
                {"Id":"163","Título": "La red social", "Género": "Drama", "Año": "2010"},
                {"Id":"164","Título": "Bohemian Rhapsody", "Género": "Musical", "Año": "2018"},
                {"Id":"165","Título": "Shazam!", "Género": "Acción", "Año": "2019"},
                {"Id":"166","Título": "El Viaje de Chihiro", "Género": "Animación", "Año": "2001"},
                {"Id":"167","Título": "La Gran Estafa", "Género": "Crimen", "Año": "2001"},
                {"Id":"168","Título": "Eterno Resplandor de una Mente sin Recuerdos", "Género": "Drama", "Año": "2004"},
                {"Id":"169","Título": "El Gran Hotel Budapest", "Género": "Comedia", "Año": "2014"},
                {"Id":"170","Título": "La La Land", "Género": "Musical", "Año": "2016"},
                {"Id":"171","Título": "El Lobo de Wall Street", "Género": "Crimen", "Año": "2013"},
                {"Id":"172","Título": "El Renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"173","Título": "El Lado Bueno de las Cosas", "Género": "Comedia", "Año": "2012"},
                {"Id":"174","Título": "La Vida de Pi", "Género": "Aventura", "Año": "2012"},
                {"Id":"175","Título": "Birdman", "Género": "Comedia", "Año": "2014"},
                {"Id":"176","Título": "El Cisne Negro", "Género": "Drama", "Año": "2010"},
                {"Id":"177","Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"},
                {"Id":"178","Título": "Dunkerque", "Género": "Bélica", "Año": "2017"},
                {"Id":"179","Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"},
                {"Id":"180","Título": "El Pianista", "Género": "Drama", "Año": "2002"},
                {"Id":"181","Título": "En Busca de la Felicidad", "Género": "Drama", "Año": "2006"},
                {"Id":"182","Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999"},
                {"Id":"183","Título": "El Silencio de los Corderos", "Género": "Suspense", "Año": "1991"},
                {"Id":"184","Título": "Matrix", "Género": "Ciencia ficción", "Año": "1999"},
                {"Id":"185","Título": "El Gran Gatsby", "Género": "Drama", "Año": "2013"},
                {"Id":"186","Título": "Drive", "Género": "Acción", "Año": "2011"},
                {"Id":"187","Título": "El Resplandor", "Género": "Terror", "Año": "1980"},
                {"Id":"188","Título": "El Origen", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"189","Título": "Cisne Negro", "Género": "Drama", "Año": "2010"},
                {"Id":"190","Título": "Whiplash", "Género": "Drama", "Año": "2014"},
                {"Id":"191","Título": "La Red Social", "Género": "Drama", "Año": "2010"},
                {"Id":"192","Título": "El Viaje de Chihiro", "Género": "Animación", "Año": "2001"},
                {"Id":"193","Título": "El Show de Truman", "Género": "Drama", "Año": "1998"},
                {"Id":"194","Título": "El Origen", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"195","Título": "El Renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"196","Título": "Parásitos", "Género": "Drama", "Año": "2019"},
                {"Id":"197","Título": "El Quinto Elemento", "Género": "Ciencia ficción", "Año": "1997"},
                {"Id":"198","Título": "El Náufrago", "Género": "Aventura", "Año": "2000"},
                {"Id":"199","Título": "Gladiador", "Género": "Acción", "Año": "2000"},
                {"Id":"200","Título": "El Resplandor", "Género": "Terror", "Año": "1980"},
                {"Id":"201","Título": "Matrix", "Género": "Ciencia ficción", "Año": "1999"},
                {"Id":"202","Título": "El Gran Hotel Budapest", "Género": "Comedia", "Año": "2014"},
                {"Id":"203","Título": "El Lobo de Wall Street", "Género": "Crimen", "Año": "2013"},
                {"Id":"204","Título": "El Show de Truman", "Género": "Drama", "Año": "1998"},
                {"Id":"205","Título": "El Renacido", "Género": "Aventura", "Año": "2015"},
                {"Id":"206","Título": "En Busca de la Felicidad", "Género": "Drama", "Año": "2006"},
                {"Id":"207","Título": "El Club de la Pelea", "Género": "Drama", "Año": "1999"},
                {"Id":"208","Título": "El Cisne Negro", "Género": "Drama", "Año": "2010"},
                {"Id":"209","Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"},
                {"Id":"210","Título": "El Lado Bueno de las Cosas", "Género": "Comedia", "Año": "2012"},
                {"Id":"211","Título": "Birdman", "Género": "Comedia", "Año": "2014"},
                {"Id":"212","Título": "La Vida de Pi", "Género": "Aventura", "Año": "2012"},
                {"Id":"213","Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"},
                {"Id":"214","Título": "Dunkerque", "Género": "Bélica", "Año": "2017"},
                {"Id":"215","Título": "El Pianista", "Género": "Drama", "Año": "2002"},
                {"Id":"216","Título": "Drive", "Género": "Acción", "Año": "2011"},
                {"Id":"217","Título": "La Red Social", "Género": "Drama", "Año": "2010"},
                {"Id":"218","Título": "Parásitos", "Género": "Drama", "Año": "2019"},
                {"Id":"219","Título": "El Quinto Elemento", "Género": "Ciencia ficción", "Año": "1997"},
                {"Id":"220","Título": "El Náufrago", "Género": "Aventura", "Año": "2000"},
                {"Id":"221","Título": "Gladiador", "Género": "Acción", "Año": "2000"},
                {"Id":"222","Título": "Forrest Gump", "Género": "Drama", "Año": "1994"},
                {"Id":"223","Título": "Inception", "Género": "Ciencia ficción", "Año": "2010"},
                {"Id":"224","Título": "Mad Max: Fury Road", "Género": "Acción", "Año": "2015"},
                {"Id":"225","Título": "La Forma del Agua", "Género": "Fantasía", "Año": "2017"},
                {"Id":"226","Título": "Guardianes de la Galaxia", "Género": "Acción", "Año": "2014"},
                {"Id":"227","Título": "Los Increíbles 2", "Género": "Animación", "Año": "2018"},
                {"Id":"228","Título": "Black Panther", "Género": "Acción", "Año": "2018"},
                {"Id":"229","Título": "Spider-Man: Into the Spider-Verse", "Género": "Animación", "Año": "2018"},
                {"Id":"230","Título": "El Discurso del Rey", "Género": "Drama", "Año": "2010"},
                {"Id":"231","Título": "Interestelar", "Género": "Ciencia ficción", "Año": "2014"},
                {"Id":"232","Título": "El Gran Hotel Budapest", "Género": "Comedia", "Año": "2014"},
                {"Id":"233","Título": "Whiplash", "Género": "Drama", "Año": "2014"},
                {"Id":"234","Título": "Pulp Fiction", "Género": "Crimen", "Año": "1994"},
                {"Id":"235","Título": "Los Siete Magníficos", "Género": "Aventura", "Año": "1960"},
    ]

@app.get("/peliculas")
async def imprimir():
    return peliculas

@app.get("/peliculas/{id}")
async def get_movies_by_id(id: str):
    filtered_movies = [movie for movie in peliculas if movie["Id"] == id]
    return filtered_movies

@app.get("/peliculas/id/{title}")
async def get_movies_by_title(title: str):
    filtered_movies = [movie for movie in peliculas if movie["Título"] == title]
    return filtered_movies


@app.get("/peliculas/id/titulo/{genre}")
async def get_movies_by_genre(genre: str):
    filtered_movies = [movie for movie in peliculas if movie["Género"] == genre]
    return filtered_movies


@app.get("/peliculas/id/titulo/genero/{year}")
async def get_movies_by_year(year: str):
    filtered_movies = [movie for movie in peliculas if movie["Año"] == year]
    return filtered_movies

@app.get("/peliculas/id/titulo/{genre}/{year}")
async def get_movies_by_genre_and_year(genre: str,year: str):
    filtered_movies = [movie for movie in peliculas if movie["Año"] == year and movie["Género"]== genre]
    return filtered_movies

@app.get("/peliculas/{id}/{title}/{genre}/{year}")
async def get_movies_by_id_title_genre_and_year(id:int, title: str, genre: str,year: str):
    filtered_movies = [movie for movie in peliculas if movie["Año"] == year and movie["Género"]== genre and movie["Título"]==title and movie["Id"]==id]
    return filtered_movies

